version: "3.8"
services:
  # Definição do Serviço do Hotel Rating Aggregator
  hotel_rating_api:
    # imagem do hotel rating aggregator
    image: hotel-rating-aggregator:latest
    # configura a rede do serviço
    networks:
      - network_swarm_public
    # Configura as portas do serviço
    ports:
      - "8000:8000"
    # Configura os volumes do serviço
    volumes:
      - /swarm-hyperscale/stacks/hotel-rating/resultados:/app/resultados
      - /swarm-hyperscale/stacks/hotel-rating/logs:/app/logs
    # Configura as variáveis de ambiente
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    # Carrega variáveis de ambiente do arquivo config.env
    env_file:
      - /swarm-hyperscale/stacks/hotel-rating/config.env
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      # Define o modo de deploy do serviço
      mode: replicated
      # Define a quantidade de réplicas do serviço
      replicas: 1
      # Define a estratégia de deploy do serviço
      placement:
        constraints:
          - node.role == manager
      resources:
        # Define os limites de recursos do serviço
        limits:
          # Define o limite de CPU do serviço
          cpus: "2"
          # Define o limite de memória do serviço
          memory: 4096M
        # Define as reservas de recursos do serviço
        reservations:
          # Define a reserva de CPU do serviço
          cpus: "0.5"
          # Define a reserva de memória do serviço
          memory: 1024M
      # Define a política de reinicialização do serviço
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

networks:
  network_swarm_public:
    external: true
    name: network_swarm_public 